name: 'Check Outdated Dependencies'
description: 'A GitHub Action that clones a GitHub repository and checks for outdated dependencies based on the programming language.'
inputs:
  repo-url:
    description: 'The URL of the GitHub repository to clone and check for outdated dependencies.'
    required: true
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run extensions.sh script
      run: |
        chmod +x ./extensions.sh
        ./extensions.sh ${{ inputs.repo-url }}
